<a href="https://colab.research.google.com/github/vishal-0378/ML/blob/main/KNN_Imputers(preprocessing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [662]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [779]:
dataset = pd.read_csv('/content/kidney_disease.csv')

In [664]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [665]:
dataset.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd

In [666]:
dataset.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [667]:
dataset[["al"]].value_counts()

al
0.0    199
1.0     44
2.0     43
3.0     43
4.0     24
5.0      1
Name: count, dtype: int64

In [668]:
dataset[["al"]].isnull().sum()

al    46
dtype: int64

In [669]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["al"]])

In [670]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [671]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [672]:
data_imputed

array([[1.        ],
       [4.        ],
       [2.        ],
       [4.        ],
       [2.        ],
       [3.        ],
       [0.        ],
       [2.        ],
       [3.        ],
       [2.        ],
       [2.        ],
       [3.        ],
       [3.        ],
       [1.01694915],
       [3.        ],
       [3.        ],
       [2.        ],
       [1.01694915],
       [0.        ],
       [1.        ],
       [2.        ],
       [1.01694915],
       [4.        ],
       [0.        ],
       [4.        ],
       [0.        ],
       [0.        ],
       [3.        ],
       [1.        ],
       [1.        ],
       [1.01694915],
       [3.        ],
       [1.        ],
       [2.        ],
       [1.        ],
       [2.        ],
       [1.        ],
       [1.01694915],
       [3.        ],
       [2.        ],
       [2.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [3.        ],
       [3.        ],
       [0.        ],
       [3.        ],
       [0.        ],
       [2.        ],
       [1.01694915],
       [3.        ],
       [0.        ],
       [0.        ],
       [2.        ],
       [3.        ],
       [3.        ],
       [1.01694915],
       [2.        ],
       [1.01694915],
       [1.        ],
       [1.        ],
       [3.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [2.        ],
       [3.        ],
       [2.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [3.        ],
       [2.        ],
       [2.        ],
       [1.        ],
       [4.        ],
       [1.        ],
       [1.01694915],
       [1.        ],
       [0.        ],
       [1.01694915],
       [1.01694915],
       [1.        ],
       [3.        ],
       [2.        ],
       [1.01694915],
       [1.        ],
       [4.        ],
       [0.        ],
       [2.        ],
       [4.        ],
       [3.        ],
       [3.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [2.        ],
       [0.        ],
       [2.        ],
       [1.01694915],
       [0.        ],
       [1.01694915],
       [1.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [3.        ],
       [3.        ],
       [0.        ],
       [3.        ],
       [0.        ],
       [4.        ],
       [0.        ],
       [3.        ],
       [0.        ],
       [1.        ],
       [3.        ],
       [1.01694915],
       [2.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [4.        ],
       [1.        ],
       [2.        ],
       [0.        ],
       [1.01694915],
       [4.        ],
       [1.01694915],
       [0.        ],
       [1.01694915],
       [2.        ],
       [1.        ],
       [2.        ],
       [0.        ],
       [1.        ],
       [1.01694915],
       [1.        ],
       [2.        ],
       [5.        ],
       [1.        ],
       [3.        ],
       [1.01694915],
       [1.        ],
       [3.        ],
       [1.01694915],
       [0.        ],
       [2.        ],
       [4.        ],
       [3.        ],
       [2.        ],
       [3.        ],
       [3.        ],
       [1.        ],
       [1.01694915],
       [3.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [0.        ],
       [2.        ],
       [3.        ],
       [1.        ],
       [1.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [2.        ],
       [2.        ],
       [2.        ],
       [1.        ],
       [2.        ],
       [0.        ],
       [0.        ],
       [3.        ],
       [1.        ],
       [4.        ],
       [2.        ],
       [1.01694915],
       [4.        ],
       [4.        ],
       [3.        ],
       [0.        ],
       [1.        ],
       [2.        ],
       [2.        ],
       [3.        ],
       [1.01694915],
       [4.        ],
       [0.        ],
       [1.        ],
       [1.01694915],
       [1.01694915],
       [1.01694915],
       [4.        ],
       [1.01694915],
       [1.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [0.        ],
       [3.        ],
       [3.        ],
       [0.        ],
       [3.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [3.        ],
       [4.        ],
       [0.        ],
       [1.01694915],
       [3.        ],
       [2.        ],
       [1.01694915],
       [1.        ],
       [2.        ],
       [0.        ],
       [2.        ],
       [1.01694915],
       [2.        ],
       [1.01694915],
       [2.        ],
       [1.        ],
       [1.        ],
       [4.        ],
       [2.        ],
       [3.        ],
       [1.01694915],
       [3.        ],
       [1.        ],
       [1.        ],
       [4.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ]])

In [673]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["al"])

In [674]:
imputed_df

      al
0    1.0
1    4.0
2    2.0
3    4.0
4    2.0
..   ...
395  0.0
396  0.0
397  0.0
398  0.0
399  0.0

[400 rows x 1 columns]

In [675]:
imputed_df.value_counts()

al
0.000000    199
1.016949     46
1.000000     44
2.000000     43
3.000000     43
4.000000     24
5.000000      1
Name: count, dtype: int64

In [676]:
import numpy as np

In [677]:
# Round & clip 'al'
dataset[["al"]] = np.clip(np.round(imputed_df), 0, 5).astype(int)

In [678]:
dataset[["al"]].value_counts()

al
0     199
1      90
2      43
3      43
4      24
5       1
Name: count, dtype: int64

In [679]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(10), int64(2), object(14)
memory usage: 81.4+ KB

In [680]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["age"]])

In [681]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [682]:
data_imputed

array([[-2.03139024e-01],
       [-2.59412412e+00],
       [ 6.13294910e-01],
       [-2.03139024e-01],
       [-2.81888954e-02],
       [ 4.96661491e-01],
       [ 9.63195168e-01],
       [-1.60274005e+00],
       [ 3.01278142e-02],
       [ 8.84445238e-02],
       [-8.65056050e-02],
       [ 6.71611620e-01],
       [ 9.63195168e-01],
       [ 9.63195168e-01],
       [ 9.63195168e-01],
       [-6.69672701e-01],
       [-2.61455734e-01],
       [-2.61455734e-01],
       [ 4.96661491e-01],
       [ 6.13294910e-01],
       [ 5.54978201e-01],
       [ 4.96661491e-01],
       [-2.03139024e-01],
       [-1.77769018e+00],
       [-5.53039282e-01],
       [ 5.54978201e-01],
       [ 1.37141214e+00],
       [ 1.02151188e+00],
       [ 1.37141214e+00],
       [ 9.63195168e-01],
       [ 9.99484667e-17],
       [ 1.25477872e+00],
       [ 5.54978201e-01],
       [ 4.96661491e-01],
       [ 1.07982859e+00],
       [ 7.88245039e-01],
       [ 1.42972884e+00],
       [ 1.19646201e+00],
       [ 1.02151188e+00],
       [ 1.77962910e+00],
       [-3.19772443e-01],
       [-3.78089153e-01],
       [-2.61455734e-01],
       [-9.61256249e-01],
       [ 1.46761233e-01],
       [ 1.46761233e-01],
       [-2.03139024e-01],
       [-2.36085728e+00],
       [ 1.25477872e+00],
       [ 4.96661491e-01],
       [ 8.84445238e-02],
       [ 1.46761233e-01],
       [ 8.84445238e-02],
       [ 6.13294910e-01],
       [ 6.71611620e-01],
       [-9.61256249e-01],
       [ 1.42972884e+00],
       [ 1.42972884e+00],
       [ 1.25477872e+00],
       [ 4.38344781e-01],
       [ 9.04878458e-01],
       [ 9.04878458e-01],
       [-2.12759044e+00],
       [-3.19772443e-01],
       [ 2.05077943e-01],
       [-4.36405863e-01],
       [ 9.04878458e-01],
       [-3.78089153e-01],
       [ 7.88245039e-01],
       [-1.48610664e+00],
       [ 5.54978201e-01],
       [-3.19772443e-01],
       [ 7.29928329e-01],
       [ 9.99484667e-17],
       [ 2.63394653e-01],
       [-2.71075754e+00],
       [-2.03139024e-01],
       [ 9.04878458e-01],
       [ 1.07982859e+00],
       [ 2.63394653e-01],
       [ 1.31309543e+00],
       [-3.78089153e-01],
       [-7.86306120e-01],
       [-2.03139024e-01],
       [ 4.38344781e-01],
       [ 1.07982859e+00],
       [ 2.63394653e-01],
       [ 1.07982859e+00],
       [ 3.80028072e-01],
       [-8.65056050e-02],
       [ 6.71611620e-01],
       [ 2.63394653e-01],
       [ 1.13814530e+00],
       [ 1.25477872e+00],
       [ 7.88245039e-01],
       [ 6.13294910e-01],
       [ 4.96661491e-01],
       [ 7.88245039e-01],
       [-8.65056050e-02],
       [ 2.63394653e-01],
       [-1.01957296e+00],
       [ 1.13814530e+00],
       [-2.01095702e+00],
       [ 1.42972884e+00],
       [ 2.05077943e-01],
       [ 7.88245039e-01],
       [-8.65056050e-02],
       [ 2.05077943e-01],
       [-3.78089153e-01],
       [ 1.46761233e-01],
       [ 6.71611620e-01],
       [ 7.88245039e-01],
       [ 9.99484667e-17],
       [ 5.54978201e-01],
       [-2.30254057e+00],
       [-2.61455734e-01],
       [ 9.99484667e-17],
       [ 9.99484667e-17],
       [ 2.05077943e-01],
       [ 4.96661491e-01],
       [ 1.19646201e+00],
       [ 1.46761233e-01],
       [-1.01957296e+00],
       [-4.94722572e-01],
       [ 7.88245039e-01],
       [ 1.19646201e+00],
       [ 1.07982859e+00],
       [ 1.13814530e+00],
       [ 3.01278142e-02],
       [ 1.37141214e+00],
       [-8.65056050e-02],
       [-2.71075754e+00],
       [-8.65056050e-02],
       [ 1.07982859e+00],
       [-2.61455734e-01],
       [-2.03139024e-01],
       [-3.19772443e-01],
       [-3.78089153e-01],
       [ 1.25477872e+00],
       [-6.11355991e-01],
       [ 1.02151188e+00],
       [ 9.04878458e-01],
       [ 1.19646201e+00],
       [-6.11355991e-01],
       [ 4.96661491e-01],
       [ 3.21711362e-01],
       [ 8.84445238e-02],
       [ 4.96661491e-01],
       [ 1.02151188e+00],
       [ 7.88245039e-01],
       [-2.53580741e+00],
       [ 1.42972884e+00],
       [-7.27989411e-01],
       [ 2.05077943e-01],
       [ 2.63394653e-01],
       [-8.65056050e-02],
       [ 8.46561749e-01],
       [ 6.13294910e-01],
       [ 1.13814530e+00],
       [ 4.38344781e-01],
       [ 1.72131239e+00],
       [ 6.13294910e-01],
       [ 4.38344781e-01],
       [-3.19772443e-01],
       [-2.18590715e+00],
       [ 4.96661491e-01],
       [-1.42778993e+00],
       [-1.01957296e+00],
       [ 7.88245039e-01],
       [ 9.99484667e-17],
       [ 8.46561749e-01],
       [ 1.83794581e+00],
       [ 6.13294910e-01],
       [-2.01095702e+00],
       [ 1.46761233e-01],
       [ 4.96661491e-01],
       [-1.77769018e+00],
       [ 7.88245039e-01],
       [-5.53039282e-01],
       [ 1.19646201e+00],
       [ 1.25477872e+00],
       [-3.78089153e-01],
       [ 5.54978201e-01],
       [-1.25283980e+00],
       [ 1.46761233e-01],
       [-2.76907425e+00],
       [-2.53580741e+00],
       [-2.82739096e+00],
       [-2.53580741e+00],
       [ 7.29928329e-01],
       [-2.65244083e+00],
       [ 9.99484667e-17],
       [-3.19772443e-01],
       [-1.13620638e+00],
       [ 1.66299568e+00],
       [ 1.07982859e+00],
       [-1.44822315e-01],
       [ 3.21711362e-01],
       [ 4.38344781e-01],
       [ 7.88245039e-01],
       [ 2.24616278e+00],
       [ 7.29928329e-01],
       [ 1.54636226e+00],
       [ 9.99484667e-17],
       [ 7.88245039e-01],
       [ 5.54978201e-01],
       [ 4.96661491e-01],
       [-8.65056050e-02],
       [ 9.04878458e-01],
       [-1.89432360e+00],
       [ 4.38344781e-01],
       [ 1.46761233e-01],
       [-6.69672701e-01],
       [ 2.05077943e-01],
       [ 9.63195168e-01],
       [-2.88570767e+00],
       [ 7.29928329e-01],
       [ 6.71611620e-01],
       [-1.07788967e+00],
       [ 9.63195168e-01],
       [-9.02939539e-01],
       [ 8.46561749e-01],
       [ 1.31309543e+00],
       [ 1.13814530e+00],
       [-1.01957296e+00],
       [ 4.96661491e-01],
       [ 7.29928329e-01],
       [ 3.21711362e-01],
       [ 4.96661491e-01],
       [ 4.38344781e-01],
       [ 7.88245039e-01],
       [ 4.96661491e-01],
       [-8.65056050e-02],
       [-2.81888954e-02],
       [-8.44622830e-01],
       [-3.78089153e-01],
       [ 7.88245039e-01],
       [ 1.66299568e+00],
       [ 1.19646201e+00],
       [-1.01957296e+00],
       [ 7.88245039e-01],
       [ 3.21711362e-01],
       [ 1.02151188e+00],
       [ 6.13294910e-01],
       [ 7.29928329e-01],
       [-2.03139024e-01],
       [-2.03139024e-01],
       [ 1.46761233e-01],
       [ 4.38344781e-01],
       [ 2.63394653e-01],
       [-6.69672701e-01],
       [-1.66105676e+00],
       [-3.78089153e-01],
       [ 3.21711362e-01],
       [-2.81888954e-02],
       [-1.01957296e+00],
       [ 4.96661491e-01],
       [-7.86306120e-01],
       [-5.53039282e-01],
       [-9.61256249e-01],
       [-1.25283980e+00],
       [-1.44822315e-01],
       [ 2.05077943e-01],
       [-3.78089153e-01],
       [-5.53039282e-01],
       [-8.65056050e-02],
       [ 2.05077943e-01],
       [-2.03139024e-01],
       [ 9.99484667e-17],
       [-1.54442335e+00],
       [-1.66105676e+00],
       [-1.25283980e+00],
       [ 2.63394653e-01],
       [-2.61455734e-01],
       [-1.89432360e+00],
       [ 3.01278142e-02],
       [-1.83600689e+00],
       [-3.19772443e-01],
       [-2.03139024e-01],
       [-1.60274005e+00],
       [-2.61455734e-01],
       [ 2.05077943e-01],
       [-1.83600689e+00],
       [ 4.96661491e-01],
       [-1.07788967e+00],
       [ 8.46561749e-01],
       [ 1.13814530e+00],
       [-7.27989411e-01],
       [ 2.63394653e-01],
       [-5.53039282e-01],
       [ 1.46761233e-01],
       [-2.61455734e-01],
       [-1.25283980e+00],
       [-8.65056050e-02],
       [ 1.37141214e+00],
       [-4.36405863e-01],
       [-6.11355991e-01],
       [ 8.84445238e-02],
       [-1.01957296e+00],
       [ 1.25477872e+00],
       [-3.78089153e-01],
       [-4.36405863e-01],
       [-1.31115651e+00],
       [ 2.05077943e-01],
       [-1.07788967e+00],
       [-6.11355991e-01],
       [ 3.01278142e-02],
       [-2.61455734e-01],
       [-4.94722572e-01],
       [-2.81888954e-02],
       [-3.19772443e-01],
       [ 2.63394653e-01],
       [ 1.66299568e+00],
       [ 2.05077943e-01],
       [-7.27989411e-01],
       [-4.36405863e-01],
       [-9.61256249e-01],
       [ 3.80028072e-01],
       [ 5.54978201e-01],
       [-1.25283980e+00],
       [ 3.21711362e-01],
       [ 7.88245039e-01],
       [ 1.07982859e+00],
       [-4.94722572e-01],
       [-6.69672701e-01],
       [ 3.80028072e-01],
       [-2.61455734e-01],
       [-1.25283980e+00],
       [-1.36947322e+00],
       [-1.07788967e+00],
       [-4.94722572e-01],
       [ 4.38344781e-01],
       [-1.01957296e+00],
       [-1.66105676e+00],
       [-1.60274005e+00],
       [ 4.96661491e-01],
       [-1.54442335e+00],
       [-4.36405863e-01],
       [ 6.13294910e-01],
       [-1.54442335e+00],
       [-1.13620638e+00],
       [ 6.71611620e-01],
       [-4.36405863e-01],
       [-8.44622830e-01],
       [ 7.29928329e-01],
       [-1.71937347e+00],
       [-1.07788967e+00],
       [-4.94722572e-01],
       [-7.86306120e-01],
       [-9.61256249e-01],
       [ 7.88245039e-01],
       [-1.31115651e+00],
       [-8.44622830e-01],
       [-7.27989411e-01],
       [-1.13620638e+00],
       [-1.66105676e+00],
       [-1.01957296e+00],
       [ 8.46561749e-01],
       [-2.61455734e-01],
       [ 1.31309543e+00],
       [-9.61256249e-01],
       [-1.31115651e+00],
       [-1.07788967e+00],
       [ 9.04878458e-01],
       [ 1.25477872e+00],
       [-1.60274005e+00],
       [ 4.96661491e-01],
       [ 9.63195168e-01],
       [-1.25283980e+00],
       [ 1.37141214e+00],
       [ 1.02151188e+00],
       [-1.36947322e+00],
       [ 1.19646201e+00],
       [ 5.54978201e-01],
       [ 1.60467897e+00],
       [ 1.07982859e+00],
       [ 3.80028072e-01],
       [ 7.29928329e-01],
       [ 1.13814530e+00],
       [ 6.13294910e-01],
       [ 4.38344781e-01],
       [ 1.13814530e+00],
       [-2.03139024e-01],
       [ 1.66299568e+00],
       [ 3.21711362e-01],
       [ 6.71611620e-01],
       [-3.19772443e-01],
       [-2.12759044e+00],
       [-2.81888954e-02],
       [-6.11355991e-01],
       [ 3.01278142e-02],
       [-9.02939539e-01],
       [ 3.21711362e-01],
       [-4.94722572e-01],
       [-8.65056050e-02],
       [ 2.05077943e-01],
       [-5.53039282e-01],
       [-2.30254057e+00],
       [-2.01095702e+00],
       [ 3.80028072e-01]])

In [683]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [684]:
data_imputed

array([[48.        ],
       [ 7.        ],
       [62.        ],
       [48.        ],
       [51.        ],
       [60.        ],
       [68.        ],
       [24.        ],
       [52.        ],
       [53.        ],
       [50.        ],
       [63.        ],
       [68.        ],
       [68.        ],
       [68.        ],
       [40.        ],
       [47.        ],
       [47.        ],
       [60.        ],
       [62.        ],
       [61.        ],
       [60.        ],
       [48.        ],
       [21.        ],
       [42.        ],
       [61.        ],
       [75.        ],
       [69.        ],
       [75.        ],
       [68.        ],
       [51.48337596],
       [73.        ],
       [61.        ],
       [60.        ],
       [70.        ],
       [65.        ],
       [76.        ],
       [72.        ],
       [69.        ],
       [82.        ],
       [46.        ],
       [45.        ],
       [47.        ],
       [35.        ],
       [54.        ],
       [54.        ],
       [48.        ],
       [11.        ],
       [73.        ],
       [60.        ],
       [53.        ],
       [54.        ],
       [53.        ],
       [62.        ],
       [63.        ],
       [35.        ],
       [76.        ],
       [76.        ],
       [73.        ],
       [59.        ],
       [67.        ],
       [67.        ],
       [15.        ],
       [46.        ],
       [55.        ],
       [44.        ],
       [67.        ],
       [45.        ],
       [65.        ],
       [26.        ],
       [61.        ],
       [46.        ],
       [64.        ],
       [51.48337596],
       [56.        ],
       [ 5.        ],
       [48.        ],
       [67.        ],
       [70.        ],
       [56.        ],
       [74.        ],
       [45.        ],
       [38.        ],
       [48.        ],
       [59.        ],
       [70.        ],
       [56.        ],
       [70.        ],
       [58.        ],
       [50.        ],
       [63.        ],
       [56.        ],
       [71.        ],
       [73.        ],
       [65.        ],
       [62.        ],
       [60.        ],
       [65.        ],
       [50.        ],
       [56.        ],
       [34.        ],
       [71.        ],
       [17.        ],
       [76.        ],
       [55.        ],
       [65.        ],
       [50.        ],
       [55.        ],
       [45.        ],
       [54.        ],
       [63.        ],
       [65.        ],
       [51.48337596],
       [61.        ],
       [12.        ],
       [47.        ],
       [51.48337596],
       [51.48337596],
       [55.        ],
       [60.        ],
       [72.        ],
       [54.        ],
       [34.        ],
       [43.        ],
       [65.        ],
       [72.        ],
       [70.        ],
       [71.        ],
       [52.        ],
       [75.        ],
       [50.        ],
       [ 5.        ],
       [50.        ],
       [70.        ],
       [47.        ],
       [48.        ],
       [46.        ],
       [45.        ],
       [73.        ],
       [41.        ],
       [69.        ],
       [67.        ],
       [72.        ],
       [41.        ],
       [60.        ],
       [57.        ],
       [53.        ],
       [60.        ],
       [69.        ],
       [65.        ],
       [ 8.        ],
       [76.        ],
       [39.        ],
       [55.        ],
       [56.        ],
       [50.        ],
       [66.        ],
       [62.        ],
       [71.        ],
       [59.        ],
       [81.        ],
       [62.        ],
       [59.        ],
       [46.        ],
       [14.        ],
       [60.        ],
       [27.        ],
       [34.        ],
       [65.        ],
       [51.48337596],
       [66.        ],
       [83.        ],
       [62.        ],
       [17.        ],
       [54.        ],
       [60.        ],
       [21.        ],
       [65.        ],
       [42.        ],
       [72.        ],
       [73.        ],
       [45.        ],
       [61.        ],
       [30.        ],
       [54.        ],
       [ 4.        ],
       [ 8.        ],
       [ 3.        ],
       [ 8.        ],
       [64.        ],
       [ 6.        ],
       [51.48337596],
       [46.        ],
       [32.        ],
       [80.        ],
       [70.        ],
       [49.        ],
       [57.        ],
       [59.        ],
       [65.        ],
       [90.        ],
       [64.        ],
       [78.        ],
       [51.48337596],
       [65.        ],
       [61.        ],
       [60.        ],
       [50.        ],
       [67.        ],
       [19.        ],
       [59.        ],
       [54.        ],
       [40.        ],
       [55.        ],
       [68.        ],
       [ 2.        ],
       [64.        ],
       [63.        ],
       [33.        ],
       [68.        ],
       [36.        ],
       [66.        ],
       [74.        ],
       [71.        ],
       [34.        ],
       [60.        ],
       [64.        ],
       [57.        ],
       [60.        ],
       [59.        ],
       [65.        ],
       [60.        ],
       [50.        ],
       [51.        ],
       [37.        ],
       [45.        ],
       [65.        ],
       [80.        ],
       [72.        ],
       [34.        ],
       [65.        ],
       [57.        ],
       [69.        ],
       [62.        ],
       [64.        ],
       [48.        ],
       [48.        ],
       [54.        ],
       [59.        ],
       [56.        ],
       [40.        ],
       [23.        ],
       [45.        ],
       [57.        ],
       [51.        ],
       [34.        ],
       [60.        ],
       [38.        ],
       [42.        ],
       [35.        ],
       [30.        ],
       [49.        ],
       [55.        ],
       [45.        ],
       [42.        ],
       [50.        ],
       [55.        ],
       [48.        ],
       [51.48337596],
       [25.        ],
       [23.        ],
       [30.        ],
       [56.        ],
       [47.        ],
       [19.        ],
       [52.        ],
       [20.        ],
       [46.        ],
       [48.        ],
       [24.        ],
       [47.        ],
       [55.        ],
       [20.        ],
       [60.        ],
       [33.        ],
       [66.        ],
       [71.        ],
       [39.        ],
       [56.        ],
       [42.        ],
       [54.        ],
       [47.        ],
       [30.        ],
       [50.        ],
       [75.        ],
       [44.        ],
       [41.        ],
       [53.        ],
       [34.        ],
       [73.        ],
       [45.        ],
       [44.        ],
       [29.        ],
       [55.        ],
       [33.        ],
       [41.        ],
       [52.        ],
       [47.        ],
       [43.        ],
       [51.        ],
       [46.        ],
       [56.        ],
       [80.        ],
       [55.        ],
       [39.        ],
       [44.        ],
       [35.        ],
       [58.        ],
       [61.        ],
       [30.        ],
       [57.        ],
       [65.        ],
       [70.        ],
       [43.        ],
       [40.        ],
       [58.        ],
       [47.        ],
       [30.        ],
       [28.        ],
       [33.        ],
       [43.        ],
       [59.        ],
       [34.        ],
       [23.        ],
       [24.        ],
       [60.        ],
       [25.        ],
       [44.        ],
       [62.        ],
       [25.        ],
       [32.        ],
       [63.        ],
       [44.        ],
       [37.        ],
       [64.        ],
       [22.        ],
       [33.        ],
       [43.        ],
       [38.        ],
       [35.        ],
       [65.        ],
       [29.        ],
       [37.        ],
       [39.        ],
       [32.        ],
       [23.        ],
       [34.        ],
       [66.        ],
       [47.        ],
       [74.        ],
       [35.        ],
       [29.        ],
       [33.        ],
       [67.        ],
       [73.        ],
       [24.        ],
       [60.        ],
       [68.        ],
       [30.        ],
       [75.        ],
       [69.        ],
       [28.        ],
       [72.        ],
       [61.        ],
       [79.        ],
       [70.        ],
       [58.        ],
       [64.        ],
       [71.        ],
       [62.        ],
       [59.        ],
       [71.        ],
       [48.        ],
       [80.        ],
       [57.        ],
       [63.        ],
       [46.        ],
       [15.        ],
       [51.        ],
       [41.        ],
       [52.        ],
       [36.        ],
       [57.        ],
       [43.        ],
       [50.        ],
       [55.        ],
       [42.        ],
       [12.        ],
       [17.        ],
       [58.        ]])

In [685]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["age"])

In [686]:
imputed_df

      age
0    48.0
1     7.0
2    62.0
3    48.0
4    51.0
..    ...
395  55.0
396  42.0
397  12.0
398  17.0
399  58.0

[400 rows x 1 columns]

In [687]:
dataset[["age"]] =np.round(imputed_df).astype(int)

In [688]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80.0,1.020,1,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50.0,1.020,4,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80.0,1.010,2,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70.0,1.005,4,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80.0,1.010,2,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80.0,1.020,0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70.0,1.025,0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80.0,1.020,0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60.0,1.025,0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80.0,1.025,0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [689]:
Df= dataset.drop('id', axis=1)

In [690]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80.0,1.020,1,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50.0,1.020,4,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80.0,1.010,2,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70.0,1.005,4,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80.0,1.010,2,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80.0,1.020,0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70.0,1.025,0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80.0,1.020,0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60.0,1.025,0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80.0,1.025,0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [691]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(9), int64(3), object(14)
memory usage: 81.4+ KB

In [692]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bp"]])

In [693]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [694]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [695]:
data_imputed

array([[ 80.        ],
       [ 50.        ],
       [ 80.        ],
       [ 70.        ],
       [ 80.        ],
       [ 90.        ],
       [ 70.        ],
       [ 76.46907216],
       [100.        ],
       [ 90.        ],
       [ 60.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 70.        ],
       [ 80.        ],
       [100.        ],
       [ 60.        ],
       [ 80.        ],
       [ 90.        ],
       [ 80.        ],
       [ 70.        ],
       [100.        ],
       [ 60.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 90.        ],
       [ 90.        ],
       [100.        ],
       [ 70.        ],
       [ 90.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 90.        ],
       [ 70.        ],
       [100.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 60.        ],
       [100.        ],
       [ 90.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 70.        ],
       [ 90.        ],
       [ 80.        ],
       [100.        ],
       [ 90.        ],
       [ 80.        ],
       [ 60.        ],
       [ 70.        ],
       [ 80.        ],
       [ 90.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 60.        ],
       [ 90.        ],
       [100.        ],
       [ 90.        ],
       [ 76.46907216],
       [ 80.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 90.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [100.        ],
       [110.        ],
       [ 70.        ],
       [100.        ],
       [ 70.        ],
       [ 70.        ],
       [100.        ],
       [ 70.        ],
       [ 90.        ],
       [ 80.        ],
       [ 60.        ],
       [140.        ],
       [180.        ],
       [ 70.        ],
       [ 90.        ],
       [ 60.        ],
       [ 70.        ],
       [ 90.        ],
       [ 80.        ],
       [ 90.        ],
       [100.        ],
       [ 80.        ],
       [ 70.        ],
       [ 90.        ],
       [ 80.        ],
       [ 60.        ],
       [ 90.        ],
       [ 60.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 90.        ],
       [ 60.        ],
       [ 70.        ],
       [ 80.        ],
       [100.        ],
       [ 90.        ],
       [ 90.        ],
       [ 60.        ],
       [ 90.        ],
       [ 70.        ],
       [ 90.        ],
       [ 50.        ],
       [ 76.46907216],
       [100.        ],
       [100.        ],
       [ 80.        ],
       [ 90.        ],
       [ 60.        ],
       [ 76.46907216],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 90.        ],
       [ 80.        ],
       [ 90.        ],
       [ 90.        ],
       [100.        ],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [ 60.        ],
       [ 90.        ],
       [ 70.        ],
       [ 90.        ],
       [ 90.        ],
       [ 70.        ],
       [ 90.        ],
       [ 70.        ],
       [ 60.        ],
       [ 80.        ],
       [ 60.        ],
       [ 76.46907216],
       [ 70.        ],
       [ 80.        ],
       [ 76.46907216],
       [ 80.        ],
       [ 60.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 50.        ],
       [ 90.        ],
       [ 80.        ],
       [ 90.        ],
       [ 90.        ],
       [ 90.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [ 60.        ],
       [ 76.46907216],
       [ 50.        ],
       [ 76.46907216],
       [ 76.46907216],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [110.        ],
       [ 90.        ],
       [ 70.        ],
       [ 90.        ],
       [100.        ],
       [ 80.        ],
       [100.        ],
       [ 80.        ],
       [ 90.        ],
       [ 70.        ],
       [ 60.        ],
       [ 90.        ],
       [ 90.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [100.        ],
       [120.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 76.46907216],
       [ 70.        ],
       [100.        ],
       [ 90.        ],
       [ 90.        ],
       [ 80.        ],
       [ 70.        ],
       [ 60.        ],
       [ 90.        ],
       [ 60.        ],
       [ 90.        ],
       [100.        ],
       [ 80.        ],
       [ 70.        ],
       [ 50.        ],
       [ 60.        ],
       [ 90.        ],
       [ 90.        ],
       [100.        ],
       [100.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [100.        ],
       [ 90.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 90.        ],
       [ 90.        ],
       [100.        ],
       [110.        ],
       [ 90.        ],
       [ 70.        ],
       [ 90.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 76.46907216],
       [ 60.        ],
       [ 70.        ],
       [ 70.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 80.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 76.46907216],
       [ 70.        ],
       [ 70.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [ 60.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 70.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [ 70.        ],
       [ 60.        ],
       [ 60.        ],
       [ 60.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 60.        ],
       [ 60.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 70.        ],
       [ 70.        ],
       [ 60.        ],
       [ 80.        ],
       [ 60.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 70.        ],
       [ 70.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 80.        ],
       [ 60.        ],
       [ 80.        ],
       [ 80.        ],
       [ 70.        ],
       [ 80.        ],
       [ 60.        ],
       [ 80.        ]])

In [696]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bp"])

In [697]:
dataset[["bp"]] =np.round(imputed_df).astype(int)

In [698]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80,1.020,1,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50,1.020,4,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80,1.010,2,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70,1.005,4,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80,1.010,2,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1.020,0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70,1.025,0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80,1.020,0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60,1.025,0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80,1.025,0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [699]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(8), int64(4), object(14)
memory usage: 81.4+ KB

In [700]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bu"]])

In [701]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [702]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [703]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bu"])

In [704]:
imputed_df

       bu
0    36.0
1    18.0
2    53.0
3    56.0
4    26.0
..    ...
395  49.0
396  31.0
397  26.0
398  50.0
399  18.0

[400 rows x 1 columns]

In [705]:
dataset[["bu"]] =np.round(imputed_df).astype(int)

In [706]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(7), int64(5), object(14)
memory usage: 81.4+ KB

In [707]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["su"]])

In [708]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [709]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [710]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["su"])

In [711]:
dataset[["su"]] =np.round(imputed_df).astype(int)

In [712]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80,1.020,1,0,NaN,normal,notpresent,notpresent,121.0,36,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50,1.020,4,0,NaN,normal,notpresent,notpresent,NaN,18,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80,1.010,2,3,normal,normal,notpresent,notpresent,423.0,53,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70,1.005,4,0,normal,abnormal,present,notpresent,117.0,56,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80,1.010,2,0,normal,normal,notpresent,notpresent,106.0,26,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1.020,0,0,normal,normal,notpresent,notpresent,140.0,49,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70,1.025,0,0,normal,normal,notpresent,notpresent,75.0,31,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80,1.020,0,0,normal,normal,notpresent,notpresent,100.0,26,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60,1.025,0,0,normal,normal,notpresent,notpresent,114.0,50,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80,1.025,0,0,normal,normal,notpresent,notpresent,131.0,18,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [713]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(6), int64(6), object(14)
memory usage: 81.4+ KB

In [714]:
dataset[["pcv"]].value_counts()

pcv
41      21
52      21
48      19
44      19
40      16
43      14
42      13
45      13
32      12
33      12
36      12
28      12
50      12
34      11
37      11
30       9
29       9
46       9
35       9
31       8
24       7
39       7
26       6
38       5
51       4
53       4
47       4
49       4
54       4
25       3
27       3
22       3
19       2
23       2
20       1
15       1
\t43     1
21       1
17       1
18       1
16       1
\t?      1
14       1
9        1
Name: count, dtype: int64

In [715]:
import pandas as pd

# Your frequency table
data = {
    "41": 21, "52": 21, "48": 19, "44": 19, "40": 16, "43": 14, "42": 13, "45": 13,
    "32": 12, "33": 12, "36": 12, "28": 12, "50": 12, "34": 11, "37": 11, "30": 9,
    "29": 9, "46": 9, "35": 9, "31": 8, "24": 7, "39": 7, "26": 6, "38": 5, "51": 4,
    "53": 4, "47": 4, "49": 4, "54": 4, "25": 3, "27": 3, "22": 3, "19": 2, "23": 2,
    "20": 1, "15": 1, "\t43": 1, "21": 1, "17": 1, "18": 1, "16": 1, "\t?": 1,
    "14": 1, "9": 1
}
s = pd.Series(data, name="count")
s.index.name = "pcv"

# --- Cleaning ---
# Step 1: strip tabs/spaces
s.index = s.index.str.strip()

# Step 2: replace "?" with "0"
s = s.rename(index={"?": "0"})

# Step 3: convert index to integer
s.index = s.index.astype(int)

# Step 4: group by pcv (merge duplicates like 43 + \t43 and add new 0)
s = s.groupby(level=0).sum()

print(s.sort_index())

pcv
0      1
9      1
14     1
15     1
16     1
17     1
18     1
19     2
20     1
21     1
22     3
23     2
24     7
25     3
26     6
27     3
28    12
29     9
30     9
31     8
32    12
33    12
34    11
35     9
36    12
37    11
38     5
39     7
40    16
41    21
42    13
43    15
44    19
45    13
46     9
47     4
48    19
49     4
50    12
51     4
52    21
53     4
54     4
Name: count, dtype: int64

In [716]:
dataset[["pcv"]].value_counts()

pcv
41      21
52      21
48      19
44      19
40      16
43      14
42      13
45      13
32      12
33      12
36      12
28      12
50      12
34      11
37      11
30       9
29       9
46       9
35       9
31       8
24       7
39       7
26       6
38       5
51       4
53       4
47       4
49       4
54       4
25       3
27       3
22       3
19       2
23       2
20       1
15       1
\t43     1
21       1
17       1
18       1
16       1
\t?      1
14       1
9        1
Name: count, dtype: int64

In [717]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(6), int64(6), object(14)
memory usage: 81.4+ KB

In [718]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Step 1: Clean 'pcv'
dataset["pcv"] = (
    dataset["pcv"]
    .astype(str)         # make sure everything is string
    .str.strip()         # remove tabs/spaces
    .replace("?", "0")   # replace "?" with 0
    .replace("nan", "0") # if "nan" string exists
)

# Step 2: Convert to numeric
dataset["pcv"] = pd.to_numeric(dataset["pcv"], errors="coerce").fillna(0).astype(int)

# Step 3: Now scale
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pcv"]])

print(data_scaled[:10])

[[ 0.70934935]
 [ 0.35519115]
 [-0.0579934 ]
 [ 0.00103296]
 [ 0.17811206]
 [ 0.41421752]
 [ 0.23713842]
 [ 0.70934935]
 [ 0.06005933]
 [-0.17604614]]

In [719]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [720]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [721]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pcv"])

In [722]:
dataset[["pcv"]] =np.round(imputed_df).astype(int)

In [723]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             400 non-null    int64
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(6), int64(7), object(13)
memory usage: 81.4+ KB

In [724]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80,1.020,1,0,NaN,normal,notpresent,notpresent,121.0,36,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50,1.020,4,0,NaN,normal,notpresent,notpresent,NaN,18,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80,1.010,2,3,normal,normal,notpresent,notpresent,423.0,53,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70,1.005,4,0,normal,abnormal,present,notpresent,117.0,56,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80,1.010,2,0,normal,normal,notpresent,notpresent,106.0,26,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1.020,0,0,normal,normal,notpresent,notpresent,140.0,49,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70,1.025,0,0,normal,normal,notpresent,notpresent,75.0,31,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80,1.020,0,0,normal,normal,notpresent,notpresent,100.0,26,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60,1.025,0,0,normal,normal,notpresent,notpresent,114.0,50,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80,1.025,0,0,normal,normal,notpresent,notpresent,131.0,18,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [725]:
dataset[["wc"]].value_counts()

wc
9800     11
6700     10
9200      9
7200      9
9600      9
         ..
16700     1
2200      1
2600      1
9700      1
9900      1
Name: count, Length: 92, dtype: int64

In [726]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Step 1: Clean 'wc'
dataset["wc"] = (
    dataset["wc"]
    .astype(str)         # force to string
    .str.strip()         # remove tabs/spaces
    .replace("?", "0")   # replace "?" with 0
    .replace("nan", "0") # replace 'nan' string with 0
)

# Step 2: Convert to numeric
dataset["wc"] = pd.to_numeric(dataset["wc"], errors="coerce").fillna(0).astype(int)

# Step 3: Scale
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["wc"]])

print(data_scaled[:10])

[[ 0.36154868]
 [-0.03980046]
 [ 0.29465716]
 [ 0.11627976]
 [ 0.25006281]
 [ 0.36154868]
 [-1.37763092]
 [ 0.16087411]
 [ 0.76289782]
 [ 1.32032718]]

In [727]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [728]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [729]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["wc"])

In [730]:
dataset[["wc"]] =np.round(imputed_df).astype(int)

In [731]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             400 non-null    int64
 17  wc              400 non-null    int64
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(6), int64(8), object(12)
memory usage: 81.4+ KB

In [732]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80,1.020,1,0,NaN,normal,notpresent,notpresent,121.0,36,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50,1.020,4,0,NaN,normal,notpresent,notpresent,NaN,18,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80,1.010,2,3,normal,normal,notpresent,notpresent,423.0,53,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70,1.005,4,0,normal,abnormal,present,notpresent,117.0,56,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80,1.010,2,0,normal,normal,notpresent,notpresent,106.0,26,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1.020,0,0,normal,normal,notpresent,notpresent,140.0,49,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70,1.025,0,0,normal,normal,notpresent,notpresent,75.0,31,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80,1.020,0,0,normal,normal,notpresent,notpresent,100.0,26,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60,1.025,0,0,normal,normal,notpresent,notpresent,114.0,50,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80,1.025,0,0,normal,normal,notpresent,notpresent,131.0,18,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [733]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Step 1: Clean 'bgr'
dataset["bgr"] = (
    dataset["bgr"]
    .astype(str)         # force to string
    .str.strip()         # remove tabs/spaces
    .replace("?", pd.NA) # replace "?" with NaN
    .replace("nan", pd.NA) # replace 'nan' string with NaN
)

# Step 2: Convert to numeric
dataset["bgr"] = pd.to_numeric(dataset["bgr"], errors="coerce")

# Step 3: Impute missing values with median
dataset["bgr"] = dataset["bgr"].fillna(dataset["bgr"].median())

# Step 4: Scale
scaler = StandardScaler()
bgr_scaled = scaler.fit_transform(dataset[["bgr"]])

In [734]:
from sklearn.impute import KNNImputer

# Select only the 'bgr' column
bgr_data = dataset[["bgr"]]  # double brackets keep it 2D

# Apply KNN Imputer
imputer = KNNImputer(n_neighbors=3)
bgr_imputed = imputer.fit_transform(bgr_data)  # shape: (400, 1)

# Convert back to DataFrame and store in original dataset
dataset["bgr"] = bgr_imputed  # replaces original 'bgr' column

In [735]:
dataset[["bgr"]] =np.round(imputed_df).astype(int)

In [736]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             400 non-null    int64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             400 non-null    int64
 17  wc              400 non-null    int64
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(5), int64(9), object(12)
memory usage: 81.4+ KB

In [737]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80,1.020,1,0,NaN,normal,notpresent,notpresent,7800,36,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50,1.020,4,0,NaN,normal,notpresent,notpresent,6000,18,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80,1.010,2,3,normal,normal,notpresent,notpresent,7500,53,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70,1.005,4,0,normal,abnormal,present,notpresent,6700,56,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80,1.010,2,0,normal,normal,notpresent,notpresent,7300,26,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1.020,0,0,normal,normal,notpresent,notpresent,6700,49,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70,1.025,0,0,normal,normal,notpresent,notpresent,7800,31,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80,1.020,0,0,normal,normal,notpresent,notpresent,6600,26,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60,1.025,0,0,normal,normal,notpresent,notpresent,7200,50,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80,1.025,0,0,normal,normal,notpresent,notpresent,6800,18,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [738]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Step 1: Clean 'sod'
dataset["sod"] = (
    dataset["sod"]
    .astype(str)         # force to string
    .str.strip()         # remove tabs/spaces
    .replace("?", pd.NA) # replace "?" with NaN
    .replace("nan", pd.NA) # replace 'nan' string with NaN
)

# Step 2: Convert to numeric
dataset["sod"] = pd.to_numeric(dataset["sod"], errors="coerce")

# Step 3: Impute missing values with median
dataset["sod"] = dataset["sod"].fillna(dataset["sod"].median())

# Step 4: Scale
scaler = StandardScaler()
bgr_scaled = scaler.fit_transform(dataset[["sod"]])

In [739]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [740]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [741]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sod"])

In [742]:
dataset[["sod"]] =np.round(imputed_df).astype(int)

In [743]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             400 non-null    int64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             400 non-null    int64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             400 non-null    int64
 17  wc              400 non-null    int64
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(4), int64(10), object(12)
memory usage: 81.4+ KB

In [744]:
dataset['rbc'].value_counts()

rbc
normal      201
abnormal     47
Name: count, dtype: int64

In [745]:
# Step 1: One-hot encode the 'rbc' column
one_hot = pd.get_dummies(dataset["rbc"], prefix="rbc", drop_first=True,dtype=int)

In [746]:
one_hot

     rbc_normal
0             0
1             0
2             1
3             1
4             1
..          ...
395           1
396           1
397           1
398           1
399           1

[400 rows x 1 columns]

In [751]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             400 non-null    int64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             400 non-null    int64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             400 non-null    int64
 17  wc              400 non-null    int64
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
 26  rbc_encoded     400 non-null    int64
 27  rbc_scaled      400 non-null    float64
dtypes: float64(5), int64(11), object(12)
memory usage: 87.6+ KB

In [758]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Scale the numeric column (the one you encoded)
rbc_scaled = scaler.fit_transform(dataset[["rbc_encoded"]])

# Store back in the dataset
dataset["rbc_scaled"] = rbc_scaled

In [759]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [760]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [761]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["rbc"])

In [762]:
dataset[["rbc"]] =np.round(imputed_df).astype(int)

In [763]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             400 non-null    int64
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             400 non-null    int64
 11  bu              400 non-null    int64
 12  sc              383 non-null    float64
 13  sod             400 non-null    int64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             400 non-null    int64
 17  wc              400 non-null    int64
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
 26  rbc_encoded     400 non-null    int64
 27  rbc_scaled      400 non-null    float64
dtypes: float64(5), int64(12), object(11)
memory usage: 87.6+ KB

In [764]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_encoded,rbc_scaled
0,0,48,80,1.020,1,0,1,normal,notpresent,notpresent,7800,36,1.2,141,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,2,1.126521
1,1,7,50,1.020,4,0,1,normal,notpresent,notpresent,6000,18,0.8,137,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,2,1.126521
2,2,62,80,1.010,2,3,1,normal,notpresent,notpresent,7500,53,1.8,140,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1,-0.400965
3,3,48,70,1.005,4,0,1,abnormal,present,notpresent,6700,56,3.8,139,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1,-0.400965
4,4,51,80,1.010,2,0,1,normal,notpresent,notpresent,7300,26,1.4,140,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1,-0.400965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1.020,0,0,1,normal,notpresent,notpresent,6700,49,0.5,139,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd,1,-0.400965
396,396,42,70,1.025,0,0,1,normal,notpresent,notpresent,7800,31,1.2,141,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd,1,-0.400965
397,397,12,80,1.020,0,0,1,normal,notpresent,notpresent,6600,26,0.6,138,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd,1,-0.400965
398,398,17,60,1.025,0,0,1,normal,notpresent,notpresent,7200,50,1.0,140,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd,1,-0.400965
399,399,58,80,1.025,0,0,1,normal,notpresent,notpresent,6800,18,1.1,139,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd,1,-0.400965

In [765]:
dataset['pc'].value_counts()

pc
normal      259
abnormal     76
Name: count, dtype: int64

In [777]:
# Step 1: One-hot encode the 'rbc' column
one_hot = pd.get_dummies(dataset["pc"], drop_first=True,dtype=int)

In [781]:
scaler = StandardScaler()

# Scale the numeric column (the one you encoded)
pc_scaled = scaler.fit_transform(one_hot)

# Store back in the dataset
dataset["pc_scaled"] = pc_scaled

In [782]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [783]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [784]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pc"])

In [785]:
dataset[["pc"]] =np.round(imputed_df).astype(int)

In [786]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              400 non-null    int64
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
 26  pc_scaled       400 non-null    float64
dtypes: float64(12), int64(2), object(13)
memory usage: 84.5+ KB