In [1]:
#importing the Libraies
import numpy as np
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(indep)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR


# ------------------ SVR ------------------
param_grid = {
    'kernel': ['linear', 'rbf'],    # kernel types
    'C': [0.1, 1, 10],              # regularization
    'gamma': ['scale', 'auto']      # kernel coefficient
}

grid = GridSearchCV(estimator=SVR(),param_grid=param_grid,cv=5,scoring='r2',n_jobs=-1)

# fitting the model for grid search
grid.fit(X,dep)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf']},
             scoring='r2')

In [9]:
# Assuming 'grid' is your GridSearchCV object and has been fitted to the data
print("Best parameters:", grid.best_params_)
# Access the mean test score for the best parameters
best_index = grid.best_index_
best_r2_score = grid.cv_results_['mean_test_score'][best_index]
# Printing the best R² score
print("r2:",best_r2_score)

Best parameters: {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}
r2: 0.4737687999987389

In [10]:
table=pd.DataFrame.from_dict(grid.cv_results_)

In [11]:
table.sort_values('rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
10,0.105820,0.009661,0.016695,0.000082,10.0,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.487873,0.472341,0.485102,0.475835,0.447692,0.473769,0.014239,1
8,0.176038,0.032751,0.025260,0.007840,10.0,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.487873,0.472341,0.485102,0.475835,0.447692,0.473769,0.014239,1
6,0.301122,0.035497,0.045884,0.010784,1.0,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",-0.025629,-0.011630,0.007866,-0.014337,-0.027381,-0.014222,0.012632,3
4,0.385382,0.053370,0.082374,0.018969,1.0,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",-0.025629,-0.011630,0.007866,-0.014337,-0.027381,-0.014222,0.012632,3
9,0.137731,0.022357,0.045040,0.010455,10.0,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.050517,-0.045096,-0.016601,-0.041415,-0.048600,-0.040446,0.012321,5
11,0.116045,0.019795,0.032133,0.007624,10.0,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.050402,-0.045276,-0.016737,-0.041345,-0.048491,-0.040450,0.012248,6
0,0.208696,0.023399,0.045314,0.015597,0.1,scale,linear,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}",-0.106644,-0.102063,-0.072395,-0.097346,-0.098230,-0.095335,0.011932,7
2,0.143195,0.043542,0.022887,0.006392,0.1,auto,linear,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'}",-0.106644,-0.102063,-0.072395,-0.097346,-0.098230,-0.095335,0.011932,7
5,0.437143,0.051061,0.110988,0.026130,1.0,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",-0.108985,-0.106259,-0.075060,-0.099683,-0.100792,-0.098156,0.012047,9
7,0.279143,0.037980,0.067488,0.017019,1.0,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",-0.108974,-0.106280,-0.075075,-0.099676,-0.100778,-0.098157,0.012041,10
1,0.334092,0.056712,0.081483,0.014100,0.1,scale,rbf,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}",-0.114702,-0.112833,-0.080977,-0.105498,-0.106552,-0.104113,0.012094,11
3,0.293735,0.073054,0.098065,0.043639,0.1,auto,rbf,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}",-0.114701,-0.112836,-0.080978,-0.105498,-0.106551,-0.104113,0.012093,12

In [12]:
# Assuming 'grid' is your GridSearchCV object that has been fitted to the data
best_model = grid.best_estimator_

In [13]:
import pickle
filename="RF_G.sav"
pickle.dump(best_model,open(filename,'wb'))