In [1]:
#importing the Libraies
import numpy as np
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(indep)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
# ------------------ Random Forest Regressor ------------------
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'criterion': ['squared_error', 'absolute_error']
}

grid = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1
)
# fitting the model for grid search
grid.fit(X,dep)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_depth': [None, 10, 20],
                         'n_estimators': [50, 100, 200]},
             scoring='r2')

In [11]:
# Assuming 'grid' is your GridSearchCV object and has been fitted to the data
print("Best parameters:", grid.best_params_)
# Access the mean test score for the best parameters
best_index = grid.best_index_
best_r2_score = grid.cv_results_['mean_test_score'][best_index]
# Printing the best R² score
print("r2:",best_r2_score)

Best parameters: {'criterion': 'absolute_error', 'max_depth': 10, 'n_estimators': 200}
r2: 0.8385494280708284

In [12]:
table=pd.DataFrame.from_dict(grid.cv_results_)

In [13]:
table.sort_values('rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
14,9.517907,0.664342,0.094957,0.100206,absolute_error,10,200,"{'criterion': 'absolute_error', 'max_depth': 1...",0.858386,0.785587,0.864403,0.834324,0.850047,0.838549,0.028344,1
13,4.611763,0.779194,0.023872,0.002024,absolute_error,10,100,"{'criterion': 'absolute_error', 'max_depth': 1...",0.859199,0.785846,0.864747,0.833908,0.848513,0.838443,0.028323,2
12,2.170117,0.240250,0.016778,0.007134,absolute_error,10,50,"{'criterion': 'absolute_error', 'max_depth': 1...",0.859859,0.783662,0.861211,0.834315,0.846044,0.837018,0.028435,3
5,1.184825,0.022232,0.046193,0.003260,squared_error,10,200,"{'criterion': 'squared_error', 'max_depth': 10...",0.857744,0.775167,0.865729,0.822606,0.844893,0.833228,0.032488,4
4,0.597442,0.012304,0.023555,0.000168,squared_error,10,100,"{'criterion': 'squared_error', 'max_depth': 10...",0.857371,0.775041,0.864765,0.820739,0.843892,0.832362,0.032339,5
3,0.305570,0.020354,0.013568,0.000098,squared_error,10,50,"{'criterion': 'squared_error', 'max_depth': 10...",0.854350,0.772485,0.862323,0.822612,0.839614,0.830277,0.031913,6
2,1.415479,0.036996,0.047556,0.000403,squared_error,None,200,"{'criterion': 'squared_error', 'max_depth': No...",0.849735,0.770294,0.856616,0.819745,0.839630,0.827204,0.031053,7
8,1.518742,0.186114,0.047302,0.001208,squared_error,20,200,"{'criterion': 'squared_error', 'max_depth': 20...",0.849880,0.770319,0.856770,0.819712,0.839310,0.827198,0.031071,8
7,1.246025,0.078341,0.047488,0.004666,squared_error,20,100,"{'criterion': 'squared_error', 'max_depth': 20...",0.851029,0.769061,0.855619,0.818332,0.838412,0.826490,0.031488,9
1,1.278822,0.131329,0.049873,0.011357,squared_error,None,100,"{'criterion': 'squared_error', 'max_depth': No...",0.850836,0.768926,0.855465,0.818257,0.838723,0.826442,0.031506,10
6,0.389946,0.057896,0.020505,0.011055,squared_error,20,50,"{'criterion': 'squared_error', 'max_depth': 20...",0.848781,0.766130,0.852838,0.821488,0.834776,0.824802,0.031349,11
0,0.554070,0.083312,0.031582,0.005185,squared_error,None,50,"{'criterion': 'squared_error', 'max_depth': No...",0.848172,0.765825,0.852530,0.821471,0.835109,0.824621,0.031338,12
16,4.892834,0.797839,0.024618,0.000849,absolute_error,20,100,"{'criterion': 'absolute_error', 'max_depth': 2...",0.841942,0.767939,0.848735,0.822628,0.836597,0.823568,0.029107,13
10,4.890551,0.721811,0.031105,0.011212,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_depth': N...",0.841920,0.768017,0.848133,0.822628,0.836640,0.823468,0.028975,14
17,9.410868,1.102415,0.043473,0.006231,absolute_error,20,200,"{'criterion': 'absolute_error', 'max_depth': 2...",0.839410,0.768584,0.848036,0.823860,0.837093,0.823397,0.028481,15
11,10.823210,1.043485,0.055026,0.019184,absolute_error,None,200,"{'criterion': 'absolute_error', 'max_depth': N...",0.839365,0.768649,0.847868,0.823894,0.837081,0.823371,0.028421,16
15,2.101695,0.039215,0.014099,0.000690,absolute_error,20,50,"{'criterion': 'absolute_error', 'max_depth': 2...",0.841199,0.763773,0.846123,0.824536,0.833649,0.821856,0.029943,17
9,2.101468,0.030783,0.014399,0.000621,absolute_error,None,50,"{'criterion': 'absolute_error', 'max_depth': N...",0.841199,0.763596,0.845759,0.824536,0.833734,0.821765,0.029960,18

In [14]:
# Assuming 'grid' is your GridSearchCV object that has been fitted to the data
best_model = grid.best_estimator_

In [15]:
import pickle
filename="RF_G.sav"
pickle.dump(best_model,open(filename,'wb'))